version: '2'

services:
 frontend:
  image: peterfebin/frontend
  ports:
   - "5000:5000" 

 cataloguedb:
  image: mongo
  volumes:
   - cataloguedb_data:/data/db

 catalogue:
  image: peterfebin/catalogue
  ports:
   - "5001:5001"

 userdb:
  image: mongo
  volumes:
   - userdb_data:/data/db

 user:
  image: peterfebin/user
  ports:
   - "5002:5002"

 cartdb:
  image: mongo
  volumes:
   - cartdb_data:/data/db

 cart:
  image: peterfebin/cart
  ports:
   - "5003:5003"

 ordersdb:
  image: mongo
  volumes:
   - ordersdb_data:/data/db

 orders:
  image: peterfebin/orders
  ports:
   - "5004:5004"

 paymentdb:
  image: mongo
  volumes:
   - paymentdb_data:/data/db
   
 payment:
  image: peterfebin/payment
  ports:
   - "5005:5005"

volumes:
 db_data:
 paymentdb_data:
 ordersdb_data:
 cartdb_data:
 userdb_data:
 cataloguedb_data:
