---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: teamcloudyuga/user-jaeger-with-time-delay
        ports:
        - containerPort: 5002
      - image: jaegertracing/jaeger-agent
        name: jaeger-agent
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        command:
        - "/go/bin/agent-linux"
        - "--collector.host-port=jaeger-collector.default.svc:14267"        
---

apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
spec:
  ports:
  - port: 5002
    targetPort: 5002
    protocol: TCP
  selector:
    app: user
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: userdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: userdb
    spec:
      volumes:
        - name: userdb
          emptyDir: {}
      containers:
      - name: userdb
        image: mongo
        volumeMounts:
        - name: userdb
          mountPath: /data/db
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: userdb
  labels:
    app: userdb
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: userdb
